services:
  app:
    build:
      context: .
      # Remove args as EXEC_MODE is no longer needed
      # args:
      #   EXEC_MODE: local
    ports:
      - 8001:8001
    environment:
      PORT: 8001
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./downloads:/usr/downloads
    entrypoint: ["python", "main.py"]